### PR TITLE
Generate Keys and Addresses

### PR DESCRIPTION
**Pull request by cryptochangements34**
#8 asks for wallet generation and I [just did this over the week in PHP](https://github.com/monero-integrations/monerophp/blob/master/src/cryptonote.php), so here it is. It only does regular addresses, not subaddresses and does not currently use mnemonic seeds but the keys + address can be used in the official wallet to restore a fully functional wallet. It also isn't named all that cleverly, but this way you have it.

### CODE REVIEW

**Comment by emesik** [comment]
I see a big tab-space indentation conflict here, which prevents importing.

I'm not a fan of space indentation but in Python we must keep it uniform anyway. So, let's do it PEP8-style. Also it implies CamelCase class names and snake_case method/function names.

Other stuff I'll discuss in #11 as these two can and should be merged.

**Comment by cryptochangements34** [comment]
The formatting has been fixed as you requested and it is now compatible with both python2 and python3.

**Comment by emesik** [comment]
Since we have #11 merged already, it seems this code could become a part of the `Seed` class. It already handles hex-passphrase conversion, so key derivation seems like a natural extension.

What do you think?

**Comment by cryptochangements34** [comment]
Sure I could start putting this in the seed class if you think that would be more practical

**Comment by cryptochangements34** [comment]
Done. At this point commits should probably be squashed too

**Comment by lalanza808** [comment]
😆 https://xkcd.com/1597/

**Pull request closed without merging**
